version: "3.8"

services:
  stats-db:
    image: postgres:16
    container_name: stats-db
    environment:
      POSTGRES_DB: later
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: diplom
    ports:
      - "5432:5432"

  stats-server:
    build:
      context: ./stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/later
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: diplom