server.port=9090

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging:
level:
ru.practicum.shareit: INFO
ru.practicum.shareit.item.ItemServiceImpl: INFO

#---
spring.datasource.url=jdbc:postgresql://155.212.166.137:5432/later
spring.datasource.username=postgres
spring.datasource.password=diplom
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#---
spring.config.activate.on-profile=test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:postgresql://stats-db:5433/later
 spring.datasource.username=postgres
spring.datasource.password=diplom

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true