server.port=9090

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging:
level:
ru.practicum.shareit: INFO
ru.practicum.shareit.item.ItemServiceImpl: INFO

#---
server.port=9090

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/later}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:diplom}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=9090
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
#---
spring.config.activate.on-profile=test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/later}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:diplom}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true