server.port=9090

logging.level.ru.practicum=INFO

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://155.212.166.137:5432/later}
spring.datasource.username=postgres
spring.datasource.password=diplom
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ?????????? Spring ?????? ??? ???? ??????? ? ?????????? ???? ?????? ????? target
logging.file.name=target/spring-boot-boot.log
logging.level.root=INFO
