CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    initiator BIGINT NOT NULL,
    category BIGINT NOT NULL,

    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,

    event_date TIMESTAMP NOT NULL,

    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,

    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,

    state VARCHAR(20) NOT NULL,

    created_on TIMESTAMP NOT NULL,
    published_on TIMESTAMP,

    CONSTRAINT fk_events_initiator
        FOREIGN KEY (initiator) REFERENCES users(id),
    CONSTRAINT fk_events_category
        FOREIGN KEY (category) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    requester BIGINT NOT NULL,
    event BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL,

    created TIMESTAMP NOT NULL,

    CONSTRAINT fk_requests_requester
        FOREIGN KEY (requester) REFERENCES users(id),
    CONSTRAINT fk_requests_event
        FOREIGN KEY (event) REFERENCES events(id),
    CONSTRAINT uq_requester_event
        UNIQUE (requester, event)
);