CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    initiator BIGINT NOT NULL,
    category BIGINT NOT NULL,

    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,

    event_date TIMESTAMP NOT NULL,

    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,

    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,

    state VARCHAR(20) NOT NULL,

    created_on TIMESTAMP NOT NULL,
    published_on TIMESTAMP,

    CONSTRAINT fk_events_initiator
        FOREIGN KEY (initiator) REFERENCES users(id),
    CONSTRAINT fk_events_category
        FOREIGN KEY (category) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    requester BIGINT NOT NULL,
    event BIGINT NOT NULL,

    status VARCHAR(20) NOT NULL,

    created TIMESTAMP NOT NULL,

    CONSTRAINT fk_requests_requester
        FOREIGN KEY (requester) REFERENCES users(id),
    CONSTRAINT fk_requests_event
        FOREIGN KEY (event) REFERENCES events(id),
    CONSTRAINT uq_requester_event
        UNIQUE (requester, event)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL UNIQUE,
    pinned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilations FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    CONSTRAINT fk_events FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    id          BIGSERIAL PRIMARY KEY,
    text        VARCHAR(2000) NOT NULL,
    commentator BIGINT NOT NULL,
    event       BIGINT NOT NULL,
    created_on  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Highly recommended tracking attribute

    CONSTRAINT fk_comments_to_users FOREIGN KEY (commentator) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_to_events FOREIGN KEY (event) REFERENCES events (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comments (event);
CREATE INDEX IF NOT EXISTS idx_comments_commentator_id ON comments (commentator);
